baseURL = 'https://lackful.pages.dev/'
languageCode = 'en-us'
title = "NULLidle.com"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
#pygmentsUseClasses = true
#pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"
enableRobotsTXT = true
enableGitInfo = false
Paginate = 6

[Params]
selfHosted = true
mainSections = ["post","posts"]
dateFormat = "15 January 2024"
comments = false
readingTime = false
wordCount = true
useHLJS = true
socialShare = true
#delayDisqus = true
showRelatedPosts = true
summaryLength  = "9"
gcse = false
lastmod = false
rss = false
pagination = "10"
hideAuthor = false
authorInfo = "Expert of Linux/UNIX-based applications and infrastructure, since childhood he's been obsessed with anything computer related. Other interests include artificial intelligence, automation, containerization, scripting, web development, and virtualization technologies. Currently unemployed due to a lay-off this past November, he's looking for a good company to call home (he's been harassing Cloudflare with applications *hint hint*). He is also the owner of the NULLidle." 
description="We provide the insight you need to navigate the vast world of web and server technology."
previewCardImagePlacement = "top"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[Author]
  name = "Joshua Marcum"
  website = "https://nullidle.com/"
  email = "josh@nullidle.com"
#  facebook = ""
#  instagram = "username"
#  youtube = "user/username" # or channel/channelname
  twitter = "@polyzombic"
#  threads = "username"
  linkedin = "https://linkedin.com/in/insecurity"
  github = "https://github.com/xegenix"
  #gitlab = "username"
  #bitbucket = "username"
  #reddit = "username"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"
  #500px = "username"
  codepen = "jmarcum"
  #mastodon = "url"
  #kaggle = "username"
  #weibo = "username"
  #slack = "username"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Notes"
    url = "/notes/"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags/blog/"
    weight = 3

[[menu.main]]
    name = "Collections"
    url = "/collections/"
    weight = 4

[[menu.main]]
    name = "About NULLidle"
    url = "/about/"
    weight = 5

