baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "lackful.com"
theme = "lightbi-hugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
#pygmentsUseClasses = true
#pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"
enableRobotsTXT = true
enableGitInfo = false
Paginate = 6

[Params]
selfHosted = true
mainSections = ["post","posts"]
dateFormat = "2 January 2023"
comments = false
readingTime = false
wordCount = false
useHLJS = true
socialShare = true
delayDisqus = true
showRelatedPosts = true
summaryLength  = "9"
gcse = false
lastmod = false
rss = false
pagination = "10"
hideAuthor = false
authorInfo = "The content found on this website is brought to you by \"Unemployment\", courtesy of a reclusive hermit's new found free-time."
description="Expert insight on today's web technology, and it's security."
previewCardImagePlacement = "bottom"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[Author]
  name = "Joshua Marcum"
  website = "https://nullidle.com/"
  email = "josh@nullidle.com"
  facebook = ""
  instagram = "username"
  youtube = "user/username" # or channel/channelname
  twitter = "@polyzombic"
  threads = "username"
  linkedin = "https://linkedin.com/in/insecurity"
  github = "https://github.com/xegenix"
  #gitlab = "username"
  #bitbucket = "username"
  #reddit = "username"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"
  #500px = "username"
  #codepen = "username"
  #mastodon = "url"
  #kaggle = "username"
  #weibo = "username"
  #slack = "username"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Notes"
    url = "/notes/"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags/blog/"
    weight = 3

[[menu.main]]
    name = "Collections"
    url = "/collections/"
    weight = 4

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5

